# Cloudflare Pages configuration
name = "minecraft-typing-tutor"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
publish = "dist"

# Environment variables (if needed)
[env.production.vars]
# Add any environment variables here if needed

# Custom headers and redirects are handled by _headers and _redirects files
